# Generated by Django 6.0.1 on 2026-02-03 01:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount transferred', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the transaction occurred')),
                ('receipt_path', models.CharField(blank=True, default='', help_text='Path to the generated receipt file', max_length=255)),
                ('receiver', models.ForeignKey(help_text='User who received the funds', on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the funds', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender', 'timestamp'], name='tx_sender_time_idx'), models.Index(fields=['receiver', 'timestamp'], name='tx_receiver_time_idx'), models.Index(fields=['timestamp'], name='tx_timestamp_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance (must be >= 0.00)', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the wallet was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the wallet was last updated')),
                ('user', models.OneToOneField(help_text='The user who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'indexes': [models.Index(fields=['user'], name='wallet_user_idx')],
            },
        ),
    ]
